trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(System.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(30afd6eb-b632-46d7-b3cc-d59671fcc51a)'
    appType: 'functionAppLinux'
    appName: 'yorkshiretwist-music-library-api'
    package: '$(System.ArtifactsDirectory)/**/*.zip'
    runtimeStack: 'DOCKER|microsoft/azure-functions-dotnet-core2.0:2.0'