trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
    TargetFolder: '$(System.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Visual Studio Ultimate with MSDN(6b8a37f6-e0c1-4cb4-ba87-5013b019d142)'
    appType: 'functionApp'
    appName: 'yorkshiretwist-music-library'
    package: '$(System.ArtifactsDirectory)/**/*.zip'
    deploymentMethod: 'auto'