using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using MusicLibrary.Models;

namespace MusicLibrary.Functions
{
    public static class Tracks
    {
        [FunctionName("tracks")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            var tracks = new List<Track>
            {
                // this code is generated by ... something, then ... copied/pasted in here
                new Track
                {
                    AlbumArtists = new List<string>{ "Boris and the Johnsons" },
                    Title = "Who's Your Daddy? ('He Doesn't Pay Any Maintenance' Remix)"
                }
            };

            return new OkObjectResult(tracks);
        }
    }
}
